name: Deploy CHOPT to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/chopt:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/chopt:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure GKE Credentials
      run: |
        gcloud container clusters get-credentials chopt-gke --region us-central1 --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy via Helm
      run: |
        helm upgrade --install chopt ./helm-chart --set image.repository=gcr.io/${{ secrets.GCP_PROJECT }}/chopt
